name: Publish Spring Parent POM

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate Spring POM
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
        
    - name: Validate POM structure
      run: ./mvnw -s .github/workflows/ci-settings.xml validate
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Run dependency analysis
      run: ./mvnw -s .github/workflows/ci-settings.xml dependency:analyze-only
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Spring Boot compatibility
      run: |
        echo "Checking Spring Boot version compatibility..."
        ./mvnw -s .github/workflows/ci-settings.xml dependency:tree | grep spring-boot
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    - name: Test Spring Boot plugin integration
      run: |
        echo "Testing Spring Boot plugin integration..."
        ./mvnw -s .github/workflows/ci-settings.xml org.springframework.boot:spring-boot-maven-plugin:help
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  publish-snapshot:
    name: Publish Spring Snapshot
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: coherity-snapshots
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
        
    - name: Configure Git user
      run: |
        git config user.email "ci@coherity.io"
        git config user.name "Coherity CI"
        
    - name: Validate GitHub Token
      run: |
        echo "Validating GitHub Token access..."
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Token length: ${#GITHUB_TOKEN}"
        echo "Token: ${GITHUB_TOKEN}"
        # Test API access
        curl -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Deploy Spring snapshot to repository
      run: |
        echo "Deploying Spring Boot parent POM snapshot..."
        echo "Using Maven credentials: ${{ github.actor }}"
        ./mvnw -s .github/workflows/ci-settings.xml clean deploy -DskipTests -X
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    name: Publish Spring Release
    runs-on: ubuntu-latest
    needs: validate
    if: startsWith(github.ref, 'refs/tags/v')
    
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: coherity-releases
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
        
    - name: Configure Git user
      run: |
        git config user.email "ci@coherity.io"
        git config user.name "Coherity CI"
        
    - name: Extract version from tag
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
        
    - name: Update POM version
      run: |
        ./mvnw versions:set -DnewVersion=${{ steps.extract_version.outputs.version }} -DgenerateBackupPoms=false
        
    - name: Build and sign artifacts
      run: ./mvnw clean package gpg:sign
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Deploy Spring release to repository
      run: |
        echo "Deploying Spring Boot parent POM release..."
        echo "Using Maven credentials: ${{ github.actor }}"
        ./mvnw -s .github/workflows/ci-settings.xml deploy -DskipTests -X
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Spring Boot Parent POM ${{ steps.extract_version.outputs.version }}
        body: |
          ## Coherity Spring Boot Parent POM ${{ steps.extract_version.outputs.version }}
          
          This release contains the shared parent POM for Coherity Spring Boot projects.
          
          ### Maven Coordinates:
          ```xml
          <parent>
            <groupId>io.coherity.shared.parent</groupId>
            <artifactId>parent-pom-spring</artifactId>
            <version>${{ steps.extract_version.outputs.version }}</version>
          </parent>
          ```
          
          ### Key Features:
          - Inherits from parent-pom-java for Java 21 and testing setup
          - Spring Boot 3.2.8 with latest dependencies
          - Log4j2 logging (replaces Logback)
          - Native compilation support
          - Docker image building
          - Testcontainers integration
          
          ### Changes:
          - See commit history for detailed changes
          
          ### Requirements:
          - Java 21+
          - Maven 3.9.9+ (or use included Maven wrapper)
          - Access to parent-pom-java dependency
        draft: false
        prerelease: false

  notify:
    name: Notify Teams
    runs-on: ubuntu-latest
    needs: [publish-snapshot, publish-release]
    if: always()
    
    steps:
    - name: Notify success
      if: needs.publish-snapshot.result == 'success' || needs.publish-release.result == 'success'
      run: |
        echo "✅ Spring Boot Parent POM published successfully!"
        echo "Branch/Tag: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        
    - name: Notify failure
      if: needs.publish-snapshot.result == 'failure' || needs.publish-release.result == 'failure'
      run: |
        echo "❌ Spring Boot Parent POM publication failed!"
        echo "Branch/Tag: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        exit 1
